# permissions for end users to view cirunnerpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cirunnerpool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kindling
    app.kubernetes.io/part-of: kindling
    app.kubernetes.io/managed-by: kustomize
  name: cirunnerpool-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - cirunnerpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - cirunnerpools/status
  verbs:
  - get
