# permissions for end users to edit devstagingenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devstagingenvironment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kindling
    app.kubernetes.io/part-of: kindling
    app.kubernetes.io/managed-by: kustomize
  name: devstagingenvironment-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - devstagingenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - devstagingenvironments/status
  verbs:
  - get
